"""
Hypothesis Engine â€” KINTHIC's prediction system.

Generates testable predictions from the causal graph structure and
tracks their verification status over time.

A hypothesis is a claim KINTHIC makes about something it was never told,
based on the causal relationships in its world model.
"""

from __future__ import annotations

from datetime import datetime, timezone

from silex_engine.models.schemas import Hypothesis as HypothesisOutput, StoredHypothesis
from silex_engine.storage.database import Database
from silex_engine.world.graph import KnowledgeGraph
from silex_engine.logger import setup_logger

log = setup_logger("silex.world.hypotheses")


class HypothesisEngine:
    """Manages KINTHIC's predictions and tracks their verification."""

    def __init__(self, db: Database, graph: KnowledgeGraph):
        self.db = db
        self.graph = graph

    async def store_hypothesis(self, hypothesis: HypothesisOutput) -> StoredHypothesis:
        """Store a hypothesis generated by Gemini."""
        # Check for duplicate hypothesis
        existing = await self._find_similar(hypothesis.claim)
        if existing:
            log.debug(f"Similar hypothesis already exists: {existing.claim[:40]}...")
            return existing

        stored = StoredHypothesis(
            claim=hypothesis.claim,
            reasoning=hypothesis.reasoning,
            confidence=0.5,  # Start neutral until verified
            status="pending",
        )

        await self.db.execute(
            """
            INSERT INTO hypotheses (id, claim, reasoning, status, confidence,
                                    created_at, resolved_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                stored.id,
                stored.claim,
                stored.reasoning,
                stored.status,
                stored.confidence,
                stored.created_at,
                stored.resolved_at,
            ),
        )

        log.info(f"New hypothesis: {hypothesis.claim[:50]}...")
        return stored

    async def confirm(self, hypothesis_id: str) -> None:
        """Mark a hypothesis as confirmed."""
        now = datetime.now(timezone.utc).isoformat()
        await self.db.execute(
            """
            UPDATE hypotheses
            SET status = 'confirmed', confidence = 1.0, resolved_at = ?
            WHERE id = ?
            """,
            (now, hypothesis_id),
        )
        log.info(f"Hypothesis confirmed: {hypothesis_id[:8]}")

    async def deny(self, hypothesis_id: str) -> None:
        """Mark a hypothesis as denied."""
        now = datetime.now(timezone.utc).isoformat()
        await self.db.execute(
            """
            UPDATE hypotheses
            SET status = 'denied', confidence = 0.0, resolved_at = ?
            WHERE id = ?
            """,
            (now, hypothesis_id),
        )
        log.info(f"Hypothesis denied: {hypothesis_id[:8]}")

    async def get_pending(self) -> list[StoredHypothesis]:
        """Get all pending (unverified) hypotheses."""
        rows = await self.db.fetch_all(
            "SELECT * FROM hypotheses WHERE status = 'pending' ORDER BY created_at DESC"
        )
        return [self._row_to_hypothesis(r) for r in rows]

    async def get_by_id(self, hypothesis_id: str) -> StoredHypothesis | None:
        """Return a hypothesis by primary key, or None."""
        row = await self.db.fetch_one(
            "SELECT * FROM hypotheses WHERE id = ?", (hypothesis_id.strip(),)
        )
        if row is None:
            return None
        return self._row_to_hypothesis(row)

    async def get_all(self) -> list[StoredHypothesis]:
        """Get all hypotheses."""
        rows = await self.db.fetch_all(
            "SELECT * FROM hypotheses ORDER BY created_at DESC"
        )
        return [self._row_to_hypothesis(r) for r in rows]

    async def count_pending(self) -> int:
        """Count pending hypotheses."""
        row = await self.db.fetch_one(
            "SELECT COUNT(*) as cnt FROM hypotheses WHERE status = 'pending'"
        )
        return row["cnt"] if row else 0

    async def _find_similar(self, claim: str) -> StoredHypothesis | None:
        """Check if a similar hypothesis already exists."""
        claim_words = set(claim.lower().split())
        if not claim_words:
            return None

        rows = await self.db.fetch_all(
            "SELECT * FROM hypotheses WHERE status = 'pending'"
        )
        for row in rows:
            existing_words = set(row["claim"].lower().split())
            if not existing_words:
                continue
            overlap = claim_words & existing_words
            smaller = min(len(claim_words), len(existing_words))
            if smaller > 0 and len(overlap) / smaller >= 0.75:
                return self._row_to_hypothesis(row)

        return None

    @staticmethod
    def _row_to_hypothesis(row: dict) -> StoredHypothesis:
        return StoredHypothesis(
            id=row["id"],
            claim=row["claim"],
            reasoning=row["reasoning"],
            status=row["status"],
            confidence=row["confidence"],
            created_at=row["created_at"],
            resolved_at=row["resolved_at"],
        )

